name: SDKs Instrumented Tests
description: 'Runs various Kotlin SDK instrumented tests'

inputs:
  shouldUseCache:
    description: 'Flag to use and save cache gradle'
    default: 'true'
  name:
    description: 'Name of test and emulator'
    required: true
  command:
    description: 'Gradle task being run'
    required: true
  report:
    description: 'Path to report'
    required: true
  projectId:
    description: 'WalletConnect projectId'
    required: true
  testTimeoutSeconds:
    description: 'Seconds for test timeout'
    default: '40'
  api-level:
    description: 'Emulator Android API '
    default: '32'
  target:
    description: 'Emulator target'
    default: 'google_apis'
  profile:
    description: 'Emulator profile'
    default: 'Nexus 6'
  arch:
    description: 'Emulator CPU architecture'
    default: 'arm64-v8a'
runs:
  using: "composite"
  steps:
    - name: Gradle cache
      if: ${{ inputs.shouldUseCache }}
      uses: gradle/gradle-build-action@v2

    - name: Create log file
      shell: bash
      run: |
        touch emulator.log
        chmod 777 emulator.log
        adb logcat -s "WalletConnectV2" >> emulator.log &

    - name: Instrumented tests
      env:
        WC_CLOUD_PROJECT_ID: ${{ inputs.projectId }}
        TEST_TIMEOUT_SECONDS: ${{ inputs.testTimeoutSeconds }}
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.api-level }}
        target: ${{ inputs.target }}
        arch: ${{ inputs.arch }}
        profile: ${{ inputs.profile }}
        avd-name: ${{ github.run_id }}-${{ github.run_number }}
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: true
        script: ./gradlew ${{ inputs.command }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{ inputs.name }}
        path: |
          **/reports/**
          emulator.log
